# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-10-20 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20160502_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, upload_to='photo')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(height_field='url_height', null=True, upload_to='activityimg/', width_field='url_wid'),
        ),
    ]
